AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Automation for Dev enviroment"
Metadata: 
  

Parameters: 
  DevweserverKeyname:
    Description: Please select the keypair
    Type: AWS::EC2::KeyPair::KeyName
  EnviromentName:
    Description: Please select your choice enviroment
    Type: String
    AllowedValues: 
      - Dev
      - Prod
      - Stage 

Mappings: 
  DevWebserverGoldenAMIMap: 
    us-east-1:
      goldenAMI: ami-0fc5d935ebf8bc3bc
    us-east-2:
      goldenAMI: ami-0e83be366243f524a
    us-west-1:
      goldenAMI: ami-0cbd40f694b804622
    us-west-2:
      goldenAMI: ami-0efcece6bed30fd98

Conditions: 
  CreateDevProdStagerResources:
    !Equals [!Ref EnviromentName , Prod]

Resources: 
  DevWebServer1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref DevweserverKeyname
      ImageId: !FindInMap [ DevWebserverGoldenAMIMap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebServer1

  DevWebServer2:
    Type: AWS::EC2::Instance
    Condition: CreateDevProdStagerResources
    Properties:
      KeyName: !Ref DevweserverKeyname
      ImageId: !FindInMap [ DevWebserverGoldenAMIMap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebServer2  

  DevWebServer3:
    Type: AWS::EC2::Instance
    Condition: CreateDevProdStagerResources
    Properties: 
      KeyName: !Ref DevweserverKeyname
      ImageId: !FindInMap [ DevWebserverGoldenAMIMap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebServer3                 

Outputs: { }
